export const Routes = {
  
  auth: {
    signIn: '/sign-in',
    signUp: '/sign-up',
    forgotPassword: '/forgot-password',
  },
  public: {
    home: '/',
    payments: '/payments',
    about: '/about',
    test: '/test',
    tours: '/tours',
    scuba: '/scuba',
    watersports: '/water-sports',
    explore: '/explore',
    pricing: '/pricing',
    contract: '/contract',
    fishing: '/fishing',
    profile: 'profile',
    contact: '/contact',
    kilifi: '/kilifi',
    snorkeling: '/snorkeling',
    addtrip: '/add-trip',
    news: '/news',
    help: '/help',
    book: '/book',
    privacy: '/privacy',
    notFound: '/404',
    userID: (userID: string) => `/user/${userID}`,
    listingDetails: (slug: string) => `/listing/${slug}`,
    addListing: '/add-listing',
    dashboard: '/account',
    inbox: '/account/inbox',
    listings: '/account/listings',
    reservations: '/account/reservations',
    accountSettings: '/account/settings',
    trips: '/trips',
    wishlist: '/wishlist',
  },
  settings:{
    payments:'/components/settings/payment-payouts',
  }
  // private: {
  //   addListing: '/add-listing',
  //   dashboard: '/account',
  //   inbox: '/account/inbox',
  //   listings: '/account/listings',
  //   reservations: '/account/reservations',
  //   accountSettings: '/account/settings',
  //   trips: '/trips',
  //   wishlist: '/wishlist',
  // },
};
